bot:
  token: TOKEN
  admins:
    - 1234567890

db:
  redis_url: redis://redis:6379/0

services:
  alerts:
    base_url: https://api.ukrainealarm.com/
    api_token: 1234567890abcdefg
    secret: 1234567890abcdefg
    region: 31

http:
  base_url: https://bots.example.com/airalert
  host: 127.0.0.1
  port: 8080
