version: "3"

services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data

  app:
    image: naualertsbot:latest
    command: [ "naualertsbot", "--config", "/config.yml" ]
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - ./config.yml:/config.yml

volumes:
  redis-data:
