version: "3.8"
services:
  redis:
    image: redis:latest
    networks:
      - naualertsbot
    volumes:
      - naualertsbot-data:/data

  naualertsbot:
    image: ${IMAGE}:${TAG}
    command: [ "naualertsbot", "--config", "/config.yml", "--log-level", "INFO" ]
    depends_on:
      - redis
    networks:
      - naualertsbot
      - traefik-public
    configs:
      - source: naualertsbot
        target: /config.yml
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.naualertsbot.rule=Host(`bots.example.com`) && PathPrefix(`/naualertsbot`)"
        - "traefik.http.routers.naualertsbot.entrypoints=web"
        - "traefik.http.services.naualertsbot.loadbalancer.server.port=8080"
        - "traefik.http.routers.naualertsbot.service=naualertsbot"

volumes:
  naualertsbot-data:

configs:
  naualertsbot:
    external: true

networks:
  traefik-public:
    external: true
  naualertsbot:
